<?php

namespace Ziming\LaravelMyinfoSg\Enums;

/**
 * For my personal use, don't use it
 * @internal
 */
enum EducationalLevelEnum: string
{
    case NO_FORMAL_QUALIFICATION_PRE_PRIMARY_LOWER_PRIMARY = 'NO FORMAL QUALIFICATION / PRE-PRIMARY / LOWER PRIMARY';
    case PRIMARY = 'PRIMARY';
    case POST_SECONDARY = 'POST-SECONDARY';
    case SECONDARY = 'SECONDARY';
    case POST_SECONDARY_NON_TERTIARY_GENERAL_VOCATION = 'POST-SECONDARY (NON-TERTIARY): GENERAL & VOCATION';
    case POLYTECHNIC_DIPLOMA = 'POLYTECHNIC DIPLOMA';
    case PROFESSIONAL_QUALIFICATION_AND_OTHER_DIPLOMA = 'PROFESSIONAL QUALIFICATION AND OTHER DIPLOMA';
    case BACHELOR_OR_EQUIVALENT = 'BACHELOR OR EQUIVALENT';
    case POSTGRADUATE_DIPLOMA_CERTIFICATE_EXCLUDING_MASTERS_AND_DOCTORATE = "POSTGRADUATE DIPLOMA / CERTIFICATE (EXCLUDING MASTER'S AND DOCTORATE)";
    case MASTER_AND_DOCTORATE_OR_EQUIVALENT = 'MASTER AND DOCTORATE OR EQUIVALENT';
    case MODULAR_CERTIFICATION_NON_AWARD_COURSES_NON_FULL_QUALIFICATIONS = 'MODULAR CERTIFICATION (NON-AWARD COURSES / NON-FULL QUALIFICATIONS)';
}
